### ISSUE TITLE
Vulnerable Error Handling in Bank Keerper

### ISSUE THREAD

**Issue by Hellobloc** [CascadiaFoundation/cascadia#29]
## Introduction 
The following code lacks error handling, which means that FeeCollectorName can distribute Gas token even if it does not have any available balance.
https://github.com/CascadiaFoundation/cascadia/blob/36f56da7790251506d7c52d20a9fbc9979d74c17/x/inflation/keeper/keeper.go#L151C3-L151C92
```golang
func (k Keeper) AddContractIncentives(ctx sdk.Context, amount sdk.Coin, contractnumber uint64) (sdk.Coin, error) {
	params := k.GetParams(ctx)
        ...

		[*]k.bankKeeper.SendCoinsFromModuleToAccount(ctx, types.ModuleName, address, contractReward)
		return amount, nil
	}

	return sdk.Coin{Denom: params.MintDenom, Amount: math.ZeroInt()}, nil
}
```
This could lead to an over-minting vulnerability.

## Recommendation
We recommend checking the sencoinxx method under BankKeeper using a more standardized error handling approach
## Related Links

https://github.com/ignite/cli/issues/2828

https://github.com/crytic/building-secure-contracts/tree/master/not-so-smart-contracts/cosmos/missing_error_handler

**Comment by Hellobloc** [comment]
I don't see a call to 'SendCoins()' at this repo, but it seems you guys don't notice the error handling. So if there is a need to use the 'SendCoins()' method, or the 'SendCoinsFromAccounttoXX()'' method in future development, I would strongly recommend reviewing this issue to prevent a more serious vulnerability.

**Comment by loveFeynman** [comment]
If the module does not have enough balance, the transfer would fail. And the rest amount would be minted and distributed to the validator. But I think we cannot say that as an over-minting vulnerability.

**Comment by Hellobloc** [comment]
> If the module does not have enough balance, the transfer would fail. And the rest amount would be minted and distributed to the validator. But I think we cannot say that as an over-minting vulnerability.

Yes, I mean it could lead to an over-minting vulnerability, so there may be some constraints to form a vulnerability, but there are risks to such an implementation.

**Comment by loveFeynman** [comment]
I think you would let me know what you mean by over-minting vulnerability in this project

**Comment by lakefishingman522** [comment]
Hey, @Hellobloc 
I have fixed the above problem as follows:

https://github.com/CascadiaFoundation/cascadia/blob/temp/errhandle/x/inflation/keeper/keeper.go#L151

```golang
func (k Keeper) AddContractIncentives(ctx sdk.Context, amount sdk.Coin, contractnumber uint64) (sdk.Coin, error) {
	params := k.GetParams(ctx)

	...
		_err := k.bankKeeper.SendCoinsFromModuleToAccount(ctx, types.ModuleName, address, contractReward)
		if _err != nil {
			return sdk.Coin{Denom: params.MintDenom, Amount: math.ZeroInt()}, _err
		}

		return amount, nil
	}

	return sdk.Coin{Denom: params.MintDenom, Amount: math.ZeroInt()}, nil
}
```
